version: "2"
services: 
    postgres:
        image: postgres:9.6.3
        restart: always
        environment:
            - POSTGRES_USER=${USERNAME}
            - POSTGRES_PASSWORD=${PASSWORD}
            - POSTGRES_DB=${DATABASE}
        volumes:
            - ./src/utils/dbSetup.sql:/docker-entrypoint-initdb.d/dbSetup.sql
        ports:
            - "5432:5432"
